In [82]:
%run Calculating.ipynb

In [83]:
%run Plotting.ipynb

In [84]:
R = np.array([
    [0., 0, 0],
    [1, 1, 1],
])

In [85]:
springs = [(0,1)]

In [95]:
H, l, v, D = calc(R, springs, threshold=.0001)

[[ 0.707  0.     0.     0.707  0.     0.   ]
 [ 0.     0.707  0.     0.     0.707  0.   ]
 [ 0.     0.     0.707  0.     0.     0.707]
 [ 0.092 -0.54   0.447 -0.092  0.54  -0.447]
 [-0.57   0.365  0.205  0.57  -0.365 -0.205]
 [-0.093 -0.447  0.54   0.093  0.447 -0.54 ]]
0.5919351792724904
0.9346540424191433
1.102502744256251


In [96]:
D.shape

(9, 6)

In [97]:
plot(R, D)